name: "CI Build and Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_cpp:
    name: Build C++ binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-20 nlohmann-json3-dev libboost-all-dev libspdlog1.12 libspdlog-dev libglm-dev libfreeimageplus-dev googletest libgmock-dev libgl-dev libopengl-dev libglew-dev libglfw3-dev libglfw3 libfreetype-dev libfreetype6-dev liblua5.1-dev ninja-build cmake

      - name: Configure build
        run: cmake -G Ninja -S $PWD -B $PWD/build

      - name: Build
        run: ninja -C $PWD/build all

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build
          path: build/

  test_pygenerator:
    name: PyGenerator unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r generator/pygenerator/dev-requirements.txt

      - name: Run pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/generator/pygenerator/src:$PWD/generator/pygenerator/test
          cd generator/pygenerator/test
          pytest .

  test_cpp:
    name: C++ unit tests
    runs-on: ubuntu-latest
    needs: build_cpp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake nlohmann-json3-dev libboost-all-dev libspdlog-dev libspdlog1.12 libglm-dev libfreeimageplus-dev googletest libgmock-dev libgl-dev libopengl-dev libglew-dev libglfw3-dev libglfw3 libfreetype-dev libfreetype6-dev liblua5.1-dev

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: cpp-build
          path: build/

      - name: Run C++ tests
        run: |
          cd build
          ctest -C Debug --output-on-failure --verbose
